// src/components/MathJax.tsx
import React, { useEffect, useRef, useState } from 'react';
import { cn } from '../utils';

// 声明MathJax全局对象
declare global {
  interface Window {
    MathJax: any;
  }
}

interface MathJaxProps {
  formula: string;
  className?: string;
  inline?: boolean;
}

export const MathJax: React.FC<MathJaxProps> = ({ formula, className = '', inline = false }) => {
  const scriptRef = useRef<HTMLScriptElement>(null);
  const wrapperRef = useRef<HTMLDivElement>(null);
  const [isReady, setIsReady] = useState(false);

  // 加载MathJax库
  useEffect(() => {
    if (window.MathJax) {
      setIsReady(true);
      return;
    }

    // 创建MathJax配置
    const configScript = document.createElement('script');
    configScript.type = 'text/javascript';
    configScript.text = `
      window.MathJax = {
        tex: {
          inlineMath: [['$', '$'], ['\\(', '\\)']],
          displayMath: [['$$', '$$'], ['\\[', '\\]']],
          packages: ['base', 'ams', 'noerrors', 'noundefined']
        },
        svg: {
          fontCache: 'global',
          scale: 1.1
        },
        startup: {
          typeset: false
        }
      };
    `;
    document.head.appendChild(configScript);

    // 加载MathJax脚本
    const script = document.createElement('script');
    script.src = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js';
    script.async = true;
    script.onload = () => {
      setIsReady(true);
    };
    document.head.appendChild(script);

    return () => {
      document.head.removeChild(configScript);
      if (script.parentNode) {
        document.head.removeChild(script);
      }
    };
  }, []);

  // 渲染公式
  useEffect(() => {
    if (isReady && wrapperRef.current && window.MathJax) {
      // 清空容器
      wrapperRef.current.innerHTML = inline ? `$${formula}$` : `$$${formula}$$`;
      
      // 触发MathJax渲染
      // 安全地调用typesetClear方法
      if (window.MathJax.typesetClear) {
        window.MathJax.typesetClear();
      }
      
      // 安全地调用typesetPromise方法，如果不存在则尝试使用typeset方法
      if (window.MathJax.typesetPromise) {
        window.MathJax.typesetPromise([wrapperRef.current]).catch((err: any) => {
          console.warn('MathJax渲染错误:', err);
        });
      } else if (window.MathJax.typeset) {
        // 降级使用typeset方法
        try {
          window.MathJax.typeset([wrapperRef.current]);
        } catch (err) {
          console.warn('MathJax渲染错误:', err);
        }
      } else {
        console.warn('MathJax没有可用的渲染方法');
      }
    }
  }, [formula, isReady, inline]);

  return (
    <div 
      ref={wrapperRef} 
      className={cn(
        'mathjax-wrapper',
        'font-math',
        className
      )}
      style={{
        fontSize: '1.1em',
        color: '#3b82f6',
        fontWeight: 'normal'
      }}
    >
      {!isReady && (
        <span className="text-blue-300 opacity-70">加载中...</span>
      )}
    </div>
  );
};

export default MathJax;

// uft-xvue-ui/src/components/MathJax.vue
<template>
  <div ref="mathElement" class="mathjax-container"></div>
</template>

<script setup lang="ts">
import { ref, watch, onMounted, onUnmounted } from 'vue'

// Props
interface Props {
  formula: string
  displayMode?: boolean
  className?: string
}

const props = withDefaults(defineProps<Props>(), {
  displayMode: true,
  className: ''
})

// 模板引用
const mathElement = ref<HTMLElement>()

// 渲染MathJax
function renderMath() {
  if (!mathElement.value || !window.MathJax) {
    return
  }
  
  const element = mathElement.value
  
  // 设置公式内容
  const wrapper = document.createElement(props.displayMode ? 'div' : 'span')
  wrapper.className = props.className
  wrapper.textContent = props.formula
  
  // 清空并添加新内容
  element.innerHTML = ''
  element.appendChild(wrapper)
  
  // 触发MathJax渲染
  window.MathJax.typesetPromise([element]).catch((err: any) => {
    console.error('MathJax rendering error:', err)
  })
}

// 初始化MathJax
function initMathJax() {
  if (window.MathJax) {
    // 如果已经加载，直接渲染
    renderMath()
    return
  }
  
  // 配置MathJax
  (window as any).MathJax = {
    tex: {
      inlineMath: [['$', '$'], ['\\(', '\\)']],
      displayMath: [['$$', '$$'], ['\\[', '\\]']],
      processEscapes: true,
      packages: {'[+]': ['ams', 'noerrors']}
    },
    svg: {
      fontCache: 'global',
      scale: 1.1
    },
    startup: {
      typeset: false
    }
  }
  
  // 加载MathJax脚本
  const script = document.createElement('script')
  script.src = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js'
  script.async = true
  script.onload = () => {
    console.log('MathJax loaded successfully')
    renderMath()
  }
  script.onerror = (err) => {
    console.error('Failed to load MathJax:', err)
  }
  document.head.appendChild(script)
}

// 监听公式变化
watch(() => props.formula, () => {
  renderMath()
}, { immediate: false })

// 生命周期
onMounted(() => {
  initMathJax()
})

onUnmounted(() => {
  // 清理
  if (mathElement.value) {
    mathElement.value.innerHTML = ''
  }
})
</script>

<style scoped>
.mathjax-container {
  width: 100%;
  overflow-x: auto;
}

/* 自定义MathJax渲染样式 */
:deep(.mjx-chtml) {
  font-size: 110% !important;
}

:deep(.mjx-chtml.MJXc-display) {
  overflow-x: auto;
  overflow-y: hidden;
}
</style>
