// bak/uft-x-vue-ui/src/components/Navbar.vue
<template>
  <nav class="navbar" :class="{ scrolled: isScrolled }">
    <div class="container">
      <!-- Logo -->
      <router-link to="/" class="logo">
        <div class="logo-content">
          <span class="logo-text">UFT-X</span>
          <span class="logo-subtitle">统一场论可视化</span>
        </div>
      </router-link>

      <!-- Desktop Navigation -->
      <div class="desktop-nav">
        <router-link
          v-for="item in navItems"
          :key="item.name"
          :to="item.path"
          class="nav-link"
          :class="{ active: currentRoute === item.path }"
        >
          {{ item.label }}
        </router-link>
        <button
          class="theme-toggle"
          @click="toggleTheme"
          :title="isDark ? '切换到浅色模式' : '切换到深色模式'"
        >
          {{ isDark ? '☀️' : '🌙' }}
        </button>
      </div>

      <!-- Mobile Navigation Toggle -->
      <button
        class="mobile-menu-toggle"
        @click="mobileMenuOpen = !mobileMenuOpen"
        aria-label="菜单"
      >
        <div class="menu-icon">
          <span class="bar" :class="{ active: mobileMenuOpen }" style="--i: 0"></span>
          <span class="bar" :class="{ active: mobileMenuOpen }" style="--i: 1"></span>
          <span class="bar" :class="{ active: mobileMenuOpen }" style="--i: 2"></span>
        </div>
      </button>
    </div>

    <!-- Mobile Navigation Menu -->
    <motion.div
      class="mobile-nav"
      :class="{ open: mobileMenuOpen }"
      :initial="{ opacity: 0, height: 0 }"
      :animate="{ opacity: mobileMenuOpen ? 1 : 0, height: mobileMenuOpen ? 'auto' : '0px' }"
      :transition="{ duration: 0.3 }"
    >
      <div class="mobile-nav-content">
        <router-link
          v-for="item in navItems"
          :key="item.name"
          :to="item.path"
          class="mobile-nav-link"
          @click="mobileMenuOpen = false"
        >
          {{ item.label }}
        </router-link>
        <div class="mobile-theme-toggle">
          <span>{{ isDark ? '浅色模式' : '深色模式' }}</span>
          <button @click="toggleTheme" class="theme-btn">
            {{ isDark ? '☀️' : '🌙' }}
          </button>
        </div>
      </div>
    </motion.div>
  </nav>
</template>

<script setup lang="ts">
  import { ref, computed, onMounted, onUnmounted } from 'vue'
  import { useRoute } from 'vue-router'
  import { motion } from 'framer-motion'
  import { useVisualizationStore } from '@/stores/visualization'

  // 使用Store
  const visualizationStore = useVisualizationStore()

  // 路由
  const route = useRoute()

  // 响应式数据
  const isScrolled = ref(false)
  const mobileMenuOpen = ref(false)

  // 导航项
  const navItems = [
    { name: 'home', path: '/', label: '首页' },
    { name: 'formulaVisualization', path: '/formula-visualization', label: '公式可视化' },
    { name: 'interactiveExploration', path: '/interactive-exploration', label: '交互式探索' },
    { name: 'knowledge', path: '/knowledge', label: '知识库' }
  ]

  // 计算属性
  const currentRoute = computed(() => route.path)
  const isDark = computed(() => visualizationStore.config.theme === 'dark')

  // 方法
  function toggleTheme() {
    const newTheme = isDark.value ? 'light' : 'dark'
    visualizationStore.updateConfig({ theme: newTheme })
    document.documentElement.setAttribute('data-theme', newTheme)
  }

  function handleScroll() {
    isScrolled.value = window.scrollY > 50
  }

  // 生命周期
  onMounted(() => {
    window.addEventListener('scroll', handleScroll)
    // 设置初始主题
    document.documentElement.setAttribute('data-theme', visualizationStore.config.theme)
  })

  onUnmounted(() => {
    window.removeEventListener('scroll', handleScroll)
  })
</script>

<style scoped>
  .navbar {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    z-index: 1000;
    background-color: rgba(10, 10, 10, 0.95);
    backdrop-filter: blur(10px);
    border-bottom: 1px solid rgba(255, 255, 255, 0.1);
    transition: all 0.3s ease;
  }

  .navbar.scrolled {
    background-color: rgba(10, 10, 10, 0.98);
    box-shadow: 0 5px 20px rgba(0, 0, 0, 0.3);
  }

  .container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 1.5rem;
    display: flex;
    justify-content: space-between;
    align-items: center;
    height: 6rem;
  }

  /* Logo */
  .logo {
    text-decoration: none;
  }

  .logo-content {
    display: flex;
    flex-direction: column;
  }

  .logo-text {
    font-size: 1.5rem;
    font-weight: bold;
    color: #4dba87;
    line-height: 1.2;
  }

  .logo-subtitle {
    font-size: 0.75rem;
    color: #999;
    line-height: 1.2;
  }

  /* Desktop Navigation */
  .desktop-nav {
    display: flex;
    align-items: center;
    gap: 2.5rem;
  }

  .nav-link {
    color: #fff;
    text-decoration: none;
    font-weight: 500;
    font-size: 0.95rem;
    position: relative;
    transition: color 0.3s ease;
  }

  .nav-link:hover,
  .nav-link.active {
    color: #4dba87;
  }

  .nav-link.active::after {
    content: '';
    position: absolute;
    bottom: -8px;
    left: 0;
    width: 100%;
    height: 2px;
    background-color: #4dba87;
    transition: all 0.3s ease;
  }

  /* Theme Toggle */
  .theme-toggle {
    background: transparent;
    border: none;
    font-size: 1.25rem;
    cursor: pointer;
    padding: 0.5rem;
    color: #fff;
    transition: transform 0.3s ease;
  }

  .theme-toggle:hover {
    transform: rotate(15deg);
  }

  /* Mobile Menu Toggle */
  .mobile-menu-toggle {
    display: none;
    background: transparent;
    border: none;
    cursor: pointer;
    padding: 0.5rem;
  }

  .menu-icon {
    width: 2rem;
    height: 2rem;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    gap: 0.3rem;
    position: relative;
  }

  .bar {
    width: 100%;
    height: 2px;
    background-color: #fff;
    transition: all 0.3s ease;
    position: absolute;
  }

  .bar:nth-child(1) {
    top: 0.5rem;
  }

  .bar:nth-child(2) {
    top: 1rem;
  }

  .bar:nth-child(3) {
    top: 1.5rem;
  }

  .bar.active:nth-child(1) {
    transform: rotate(45deg);
    top: 1rem;
    background-color: #4dba87;
  }

  .bar.active:nth-child(2) {
    opacity: 0;
  }

  .bar.active:nth-child(3) {
    transform: rotate(-45deg);
    top: 1rem;
    background-color: #4dba87;
  }

  /* Mobile Navigation */
  .mobile-nav {
    overflow: hidden;
    background-color: #0a0a0a;
    border-top: 1px solid rgba(255, 255, 255, 0.1);
  }

  .mobile-nav-content {
    padding: 1.5rem;
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  .mobile-nav-link {
    color: #fff;
    text-decoration: none;
    padding: 1rem;
    border-radius: 0.5rem;
    transition: background-color 0.3s ease;
    font-weight: 500;
  }

  .mobile-nav-link:hover {
    background-color: rgba(77, 186, 135, 0.1);
    color: #4dba87;
  }

  .mobile-theme-toggle {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 1rem;
    border-radius: 0.5rem;
    background-color: rgba(255, 255, 255, 0.05);
    margin-top: 1rem;
  }

  .theme-btn {
    background: transparent;
    border: none;
    font-size: 1.5rem;
    cursor: pointer;
    padding: 0.5rem;
    color: #fff;
  }

  /* 响应式设计 */
  @media (max-width: 992px) {
    .desktop-nav {
      gap: 1.5rem;
    }
  }

  @media (max-width: 768px) {
    .container {
      padding: 0 1rem;
      height: 5rem;
    }

    .desktop-nav {
      display: none;
    }

    .mobile-menu-toggle {
      display: block;
    }

    .logo-text {
      font-size: 1.25rem;
    }

    .logo-subtitle {
      font-size: 0.7rem;
    }
  }

  @media (max-width: 480px) {
    .container {
      padding: 0 0.75rem;
    }

    .mobile-nav-content {
      padding: 1rem;
    }
  }
</style>

// src/components/Navbar.tsx
import React, { useState, useEffect } from 'react'
import { Link as RouterLink, useLocation } from 'react-router-dom'
import { motion, AnimatePresence } from 'framer-motion'
import { cn } from '../utils'

const Navbar: React.FC = () => {
  const location = useLocation()
  const [isScrolled, setIsScrolled] = useState(false)
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false)

  const navItems = [
    { path: '/', label: '🏠 首页', icon: '🏠' },
    { path: '/formulas', label: '📐 公式可视化', icon: '📐' },
    { path: '/artificial-field', label: '⚡ 人工场技术', icon: '⚡' },
    { path: '/interactive', label: '🔭 交互探索', icon: '🔭' },
    { path: '/knowledge', label: '📚 知识学习', icon: '📚' },
    { path: '/algorithm-alliance', label: '🧬 算法联盟', icon: '🧬' }
  ]

  useEffect(() => {
    // 检测滚动状态，使用更平滑的过渡
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 20)
    }

    window.addEventListener('scroll', handleScroll)
    return () => window.removeEventListener('scroll', handleScroll)
  }, [])

  // 重置移动端菜单状态当路由变化时
  useEffect(() => {
    setIsMobileMenuOpen(false)
  }, [location.pathname])

  return (
    <nav
      className={cn(
        'fixed left-0 right-0 top-0 z-50 transition-all duration-500 ease-in-out',
        isScrolled
          ? 'border-b border-gray-700/50 bg-gray-900/95 shadow-xl shadow-blue-500/10 backdrop-blur-3xl'
          : 'border-b border-gray-700/30 bg-gradient-to-b from-gray-900/80 to-gray-900/30 backdrop-blur-lg'
      )}
    >
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="flex h-20 items-center justify-between">
          {/* Logo */}
          <motion.div 
            className="flex items-center space-x-3"
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.8 }}
          >
            <motion.div 
              className="flex h-12 w-12 items-center justify-center rounded-lg bg-gradient-to-r from-blue-500 via-purple-600 to-cyan-500 shadow-lg shadow-blue-500/20"
              animate={{
                boxShadow: [
                  '0 0 20px rgba(99, 102, 241, 0.2)',
                  '0 0 40px rgba(99, 102, 241, 0.4)',
                  '0 0 20px rgba(99, 102, 241, 0.2)'
                ]
              }}
              transition={{
                duration: 2,
                repeat: Infinity,
                ease: 'easeInOut'
              }}
            >
              <span className="text-xl font-bold text-white">🌌</span>
            </motion.div>
            <div>
              <h1 className="bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-xl font-bold text-transparent">
                统一场论
              </h1>
              <p className="text-xs text-blue-400/80">Unified Field Theory</p>
            </div>
          </motion.div>

          {/* Desktop Navigation */}
          <div className="hidden items-center space-x-2 md:flex">
            {navItems.map((item, index) => {
              const isActive = location.pathname === item.path
              return (
                <motion.div
                  key={item.path}
                  initial={{ opacity: 0, y: -20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ 
                    duration: 0.5, 
                    delay: 0.1 * index 
                  }}
                >
                  <RouterLink
                    to={item.path}
                    className={cn(
                      'flex items-center space-x-2 rounded-lg px-6 py-3 text-sm font-medium transition-all duration-300 relative overflow-hidden',
                      isActive
                        ? 'border border-blue-500/30 bg-gradient-to-r from-blue-500/10 to-purple-500/10 text-blue-400 shadow-md shadow-blue-500/10'
                        : 'text-white hover:bg-gray-800/50 hover:text-blue-300 hover:shadow-lg hover:shadow-blue-500/5'
                    )}
                    onClick={() => {
                      window.scrollTo({
                        top: 0,
                        behavior: 'smooth'
                      })
                    }}
                  >
                    {/* 选中状态指示器 */}
                    {isActive && (
                      <motion.span
                        className="absolute inset-0 bg-gradient-to-r from-blue-500/10 to-purple-500/10"
                        initial={{ scaleX: 0 }}
                        animate={{ scaleX: 1 }}
                        transition={{ duration: 0.3, origin: 'left' }}
                        style={{ zIndex: -1 }}
                      />
                    )}
                    <span className="relative z-10">{item.icon}</span>
                    <span className="relative z-10">{item.label.replace(/^[^\s]+\s/, '')}</span>
                  </RouterLink>
                </motion.div>
              )
            })}
          </div>

          {/* Mobile menu button */}
          <motion.button
            onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
            className="rounded-lg p-3 text-gray-400 transition-all duration-300 hover:bg-gray-800/50 hover:text-white hover:shadow-lg hover:shadow-blue-500/10 md:hidden"
            whileTap={{ scale: 0.95 }}
            animate={{ rotate: isMobileMenuOpen ? 45 : 0 }}
          >
            <svg className="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              {isMobileMenuOpen ? (
                <motion.path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M6 18L18 6M6 6l12 12"
                  initial={{ pathLength: 0 }}
                  animate={{ pathLength: 1 }}
                  transition={{ duration: 0.3 }}
                />
              ) : (
                <motion.path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M4 6h16M4 12h16M4 18h16"
                  initial={{ pathLength: 0 }}
                  animate={{ pathLength: 1 }}
                  transition={{ duration: 0.3 }}
                />
              )}
            </svg>
          </motion.button>
        </div>

        {/* Mobile Navigation */}
        <AnimatePresence>
          {isMobileMenuOpen && (
            <motion.div
              className="border-t border-gray-700/50 bg-gray-900/95 backdrop-blur-xl md:hidden"
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: 'auto' }}
              exit={{ opacity: 0, height: 0 }}
              transition={{ duration: 0.4, ease: 'easeInOut' }}
            >
              <div className="space-y-1 px-4 py-4">
                {navItems.map((item, index) => {
                  const isActive = location.pathname === item.path
                  return (
                    <motion.div
                      key={item.path}
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ duration: 0.3, delay: 0.1 * index }}
                    >
                      <RouterLink
                        to={item.path}
                        onClick={() => setIsMobileMenuOpen(false)}
                        className={cn(
                          'block flex items-center space-x-3 rounded-lg px-5 py-4 text-base font-medium transition-all duration-300 relative overflow-hidden',
                          isActive
                            ? 'border-l-4 border-blue-500 bg-gradient-to-r from-blue-500/20 to-purple-500/20 text-blue-400 shadow-md shadow-blue-500/10'
                            : 'text-gray-300 hover:border-l-4 hover:border-blue-500/50 hover:bg-gray-800/50 hover:text-white'
                        )}
                      >
                        <span className="text-lg">{item.icon}</span>
                        <span>{item.label}</span>
                        {isActive && (
                          <motion.span
                            className="absolute inset-0 bg-gradient-to-r from-blue-500/10 to-purple-500/10"
                            initial={{ scaleX: 0 }}
                            animate={{ scaleX: 1 }}
                            transition={{ duration: 0.3, origin: 'left' }}
                            style={{ zIndex: -1 }}
                          />
                        )}
                      </RouterLink>
                    </motion.div>
                  )
                })}
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </nav>
  )
}

export default Navbar
